// flashcards.js - AI-generated dynamic flashcards

let flashcardState = {
  cards: [],
  currentIndex: 0,
  flipped: false,
  topic: '',
  difficulty: 'Mid',
  sessionKnown: [],
  sessionPractice: [],
  loading: false,
  sessionComplete: false,
};

const FLASHCARD_TOPICS = [
  { label: 'JavaScript', icon: '🟨' },
  { label: 'Python', icon: '🐍' },
  { label: 'Data Structures', icon: '📊' },
  { label: 'Algorithms', icon: '⚡' },
  { label: 'System Design', icon: '🏗️' },
  { label: 'React', icon: '⚛️' },
  { label: 'SQL & Databases', icon: '🗄️' },
  { label: 'Behavioral (HR)', icon: '🤝' },
  { label: 'CSS & HTML', icon: '🎨' },
  { label: 'Node.js', icon: '💚' },
  { label: 'TypeScript', icon: '🔷' },
  { label: 'DevOps & CI/CD', icon: '🚀' },
  { label: 'Machine Learning', icon: '🤖' },
  { label: 'REST APIs', icon: '🔌' },
  { label: 'Git & Version Control', icon: '📝' },
];

function renderFlashcards() {
  if (flashcardState.loading) return renderFlashcardsLoading();
  if (flashcardState.cards.length > 0 && !flashcardState.sessionComplete) return renderFlashcardSession();
  if (flashcardState.sessionComplete) return renderFlashcardSummary();
  return renderFlashcardSetup();
}

// ── SETUP ──────────────────────────────────────────────────────────────────

function renderFlashcardSetup() {
  return `
  <div class="animate-fade">
    <div class="page-header">
      <h1 class="page-title">📚 Flashcards</h1>
      <p class="page-subtitle">AI generates fresh Q&A cards on any topic you choose</p>
    </div>

    <div style="max-width:640px">
      <div class="card card-gradient" style="margin-bottom:20px">
        <h2 style="font-size:16px;font-weight:700;margin-bottom:16px">Choose a Topic</h2>
        <div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px" id="topic-tags">
          ${FLASHCARD_TOPICS.map(t => `
            <span class="tag ${flashcardState.topic === t.label ? 'active' : ''}" onclick="selectFlashcardTopic('${t.label}', this)">
              ${t.icon} ${t.label}
            </span>
          `).join('')}
        </div>

        <div class="form-group" style="margin-bottom:16px">
          <label class="form-label">Or enter a custom topic</label>
          <input class="input" id="custom-topic" type="text" placeholder="e.g. React Hooks, Kubernetes, OAuth..." oninput="setCustomTopic(this.value)" value="${!FLASHCARD_TOPICS.find(t=>t.label===flashcardState.topic) ? flashcardState.topic : ''}" />
        </div>

        <div class="form-group" style="margin-bottom:16px">
          <label class="form-label">Difficulty</label>
          <div class="tabs">
            <button class="tab ${flashcardState.difficulty==='Junior'?'active':''}" onclick="setFlashDiff(this,'Junior')">Beginner</button>
            <button class="tab ${flashcardState.difficulty==='Mid'?'active':''}" onclick="setFlashDiff(this,'Mid')">Intermediate</button>
            <button class="tab ${flashcardState.difficulty==='Senior'?'active':''}" onclick="setFlashDiff(this,'Senior')">Advanced</button>
          </div>
        </div>

        <div class="form-group" style="margin-bottom:20px">
          <label class="form-label">Number of cards</label>
          <div class="tabs">
            <button class="tab active" id="fcard-5" onclick="setFlashCount(this,5)">5</button>
            <button class="tab" id="fcard-8" onclick="setFlashCount(this,8)">8</button>
            <button class="tab" id="fcard-10" onclick="setFlashCount(this,10)">10</button>
          </div>
        </div>

        ${!Storage.getApiKey() ? `<div class="alert alert-warning" style="margin-bottom:16px">⚠️ No API key. <a href="#" onclick="navigateTo('settings')" style="color:var(--color-warning-light);font-weight:600">Add one in Settings</a> to generate AI questions.</div>` : ''}

        <button class="btn btn-primary btn-lg" style="width:100%" onclick="generateFlashcards()">
          ✨ Generate Cards with AI
        </button>
      </div>

      <!-- Offline fallback hint -->
      <div class="alert alert-info">
        💡 Cards are freshly generated by Gemini AI each session — every session has unique questions!
      </div>
    </div>
  </div>`;
}

let flashCardCount = 5;

function selectFlashcardTopic(topic, el) {
  document.querySelectorAll('#topic-tags .tag').forEach(t => t.classList.remove('active'));
  el.classList.add('active');
  flashcardState.topic = topic;
  const custom = document.getElementById('custom-topic');
  if (custom) custom.value = '';
}

function setCustomTopic(val) {
  if (val) {
    document.querySelectorAll('#topic-tags .tag').forEach(t => t.classList.remove('active'));
    flashcardState.topic = val;
  }
}

function setFlashDiff(btn, diff) {
  btn.parentElement.querySelectorAll('.tab').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  flashcardState.difficulty = diff;
}

function setFlashCount(btn, count) {
  document.querySelectorAll('#fcard-5,#fcard-8,#fcard-10').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  flashCardCount = count;
}

async function generateFlashcards() {
  const topic = flashcardState.topic || document.getElementById('custom-topic')?.value?.trim();
  if (!topic) { showToast('Please select or enter a topic', 'error'); return; }
  if (!Storage.getApiKey()) { showToast('Add a Gemini API key in Settings first', 'error'); return; }

  flashcardState.topic = topic;
  flashcardState.loading = true;
  flashcardState.cards = [];
  flashcardState.currentIndex = 0;
  flashcardState.flipped = false;
  flashcardState.sessionKnown = [];
  flashcardState.sessionPractice = [];
  flashcardState.sessionComplete = false;
  renderPage('flashcards');

  try {
    const cards = await Gemini.generateFlashcards(topic, flashCardCount, flashcardState.difficulty);
    flashcardState.cards = cards;
    flashcardState.loading = false;
    Storage.logActivity();
    renderPage('flashcards');
  } catch (e) {
    flashcardState.loading = false;
    showToast('Failed to generate cards: ' + e.message, 'error');

    // Fallback to static questions if available
    const category = Object.keys(QUESTIONS_BANK).find(k =>
      topic.toLowerCase().includes(k.toLowerCase()) || k.toLowerCase().includes(topic.toLowerCase().split(' ')[0])
    );
    if (category) {
      flashcardState.cards = QUESTIONS_BANK[category].slice(0, flashCardCount);
      showToast('Using offline question bank as fallback', 'success');
      renderPage('flashcards');
    } else {
      renderPage('flashcards');
    }
  }
}

function renderFlashcardsLoading() {
  return `
  <div class="animate-fade" style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:60vh;gap:20px;text-align:center">
    <div style="font-size:48px;animation:pulse 1.5s ease-in-out infinite">✨</div>
    <div>
      <div style="font-size:20px;font-weight:700;margin-bottom:8px">Generating Cards...</div>
      <div style="color:var(--text-secondary);font-size:14px">AI is creating ${flashCardCount} personalized ${flashcardState.topic} questions for you</div>
    </div>
    <div class="spinner" style="width:32px;height:32px;border-width:3px"></div>
  </div>`;
}

// ── SESSION ────────────────────────────────────────────────────────────────

function renderFlashcardSession() {
  const s = flashcardState;
  const card = s.cards[s.currentIndex];
  const progress = Math.round((s.currentIndex / s.cards.length) * 100);

  return `
  <div class="animate-fade">
    <div class="page-header" style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px">
      <div>
        <h1 class="page-title">📚 ${s.topic}</h1>
        <p class="page-subtitle">${s.difficulty} · ${s.cards.length} cards</p>
      </div>
      <button class="btn btn-secondary" onclick="flashcardState.cards=[];flashcardState.sessionComplete=false;renderPage('flashcards')">← New Topic</button>
    </div>

    <!-- Progress -->
    <div class="card" style="margin-bottom:20px;padding:14px 20px">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
        <span style="font-size:13px;color:var(--text-secondary)">Card ${s.currentIndex + 1} of ${s.cards.length}</span>
        <div style="display:flex;gap:12px;font-size:12px">
          <span style="color:var(--color-success-light)">✅ ${s.sessionKnown.length} know it</span>
          <span style="color:var(--color-warning-light)">🔄 ${s.sessionPractice.length} need practice</span>
        </div>
      </div>
      <div class="progress-bar"><div class="progress-fill" style="width:${progress}%"></div></div>
    </div>

    <!-- Card -->
    <div style="max-width:640px;margin:0 auto 24px">
      <div class="flip-card-container" onclick="flipFlashcard()">
        <div class="flip-card ${s.flipped ? 'flipped' : ''}" id="flip-card">
          <div class="flip-front">
            <div style="font-size:11px;font-weight:700;color:var(--color-primary-light);text-transform:uppercase;letter-spacing:1px;margin-bottom:16px">❓ Question</div>
            <div style="font-size:17px;font-weight:600;line-height:1.6;color:var(--text-primary)">${card.q}</div>
            <div class="flip-hint">Click to reveal answer</div>
          </div>
          <div class="flip-back">
            <div style="font-size:11px;font-weight:700;color:var(--color-accent-light);text-transform:uppercase;letter-spacing:1px;margin-bottom:16px">💡 Answer</div>
            <div style="font-size:14px;line-height:1.7;color:var(--text-primary)">${card.a}</div>
          </div>
        </div>
      </div>

      <div style="text-align:center;margin-top:12px">
        <span style="font-size:13px;color:var(--text-muted)">${s.flipped ? 'How did you do?' : 'Click the card to flip it'}</span>
      </div>
    </div>

    <!-- Action Buttons -->
    <div style="display:flex;justify-content:center;gap:16px;flex-wrap:wrap;margin-bottom:24px">
      ${s.flipped ? `
        <button class="btn btn-danger btn-lg" onclick="markFlashcard('practice')" style="min-width:160px">
          🔄 Need Practice
        </button>
        <button class="btn btn-success btn-lg" onclick="markFlashcard('known')" style="min-width:160px">
          ✅ Know It!
        </button>
      ` : `
        <button class="btn btn-secondary btn-lg" onclick="flipFlashcard()">
          👀 Show Answer
        </button>
      `}
    </div>

    ${s.currentIndex > 0 ? `
      <div style="display:flex;justify-content:center">
        <button class="btn btn-secondary btn-sm" onclick="prevFlashcard()">← Previous card</button>
      </div>
    ` : ''}
  </div>`;
}

function flipFlashcard() {
  flashcardState.flipped = !flashcardState.flipped;
  const card = document.getElementById('flip-card');
  if (card) card.classList.toggle('flipped');
  const hint = document.querySelector('.flip-hint');
  if (hint) hint.textContent = flashcardState.flipped ? 'Click to see question again' : 'Click to reveal answer';

  // Show action buttons without full re-render
  renderPage('flashcards');
}

function markFlashcard(type) {
  const s = flashcardState;
  const card = s.cards[s.currentIndex];

  if (type === 'known') {
    s.sessionKnown.push(s.currentIndex);
  } else {
    s.sessionPractice.push(s.currentIndex);
  }

  if (s.currentIndex + 1 >= s.cards.length) {
    // end of session
    const p = Storage.getProgress();
    Storage.updateProgress({
      flashcardsStudied: p.flashcardsStudied + s.cards.length,
      flashcardsKnown: p.flashcardsKnown + s.sessionKnown.length,
    });
    flashcardState.sessionComplete = true;
  } else {
    flashcardState.currentIndex++;
    flashcardState.flipped = false;
  }

  renderPage('flashcards');
}

function prevFlashcard() {
  if (flashcardState.currentIndex > 0) {
    flashcardState.currentIndex--;
    flashcardState.flipped = false;
    renderPage('flashcards');
  }
}

// ── SUMMARY ────────────────────────────────────────────────────────────────

function renderFlashcardSummary() {
  const s = flashcardState;
  const knownPct = Math.round((s.sessionKnown.length / s.cards.length) * 100);

  return `
  <div class="animate-fade">
    <div class="page-header">
      <h1 class="page-title">📚 Session Complete!</h1>
      <p class="page-subtitle">${s.topic} · ${s.difficulty}</p>
    </div>

    <div class="card card-gradient" style="text-align:center;padding:40px;margin-bottom:24px">
      <div style="font-size:64px;font-weight:900;background:var(--gradient-primary);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:8px">${knownPct}%</div>
      <div style="font-size:18px;font-weight:700;margin-bottom:8px">${knownPct >= 80 ? '🎉 Outstanding!' : knownPct >= 60 ? '👍 Good Progress!' : '💪 Keep Practicing!'}</div>
      <div style="color:var(--text-secondary);font-size:14px">You knew ${s.sessionKnown.length} of ${s.cards.length} cards</div>
    </div>

    <div class="grid-2" style="margin-bottom:24px">
      <div class="card" style="background:rgba(16,185,129,0.06);border-color:rgba(16,185,129,0.2);text-align:center;padding:24px">
        <div style="font-size:36px;font-weight:800;color:var(--color-success-light)">${s.sessionKnown.length}</div>
        <div style="color:var(--text-secondary);font-size:14px;margin-top:4px">Cards you know ✅</div>
      </div>
      <div class="card" style="background:rgba(245,158,11,0.06);border-color:rgba(245,158,11,0.2);text-align:center;padding:24px">
        <div style="font-size:36px;font-weight:800;color:var(--color-warning-light)">${s.sessionPractice.length}</div>
        <div style="color:var(--text-secondary);font-size:14px;margin-top:4px">Need more practice 🔄</div>
      </div>
    </div>

    <div style="display:flex;gap:12px;flex-wrap:wrap">
      <button class="btn btn-primary btn-lg" onclick="generateFlashcards()">🔄 New Cards (Same Topic)</button>
      <button class="btn btn-secondary btn-lg" onclick="flashcardState.cards=[];flashcardState.sessionComplete=false;renderPage('flashcards')">📚 New Topic</button>
      <button class="btn btn-secondary btn-lg" onclick="navigateTo('dashboard')">🏠 Dashboard</button>
    </div>
  </div>`;
}
