version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://postgres:postgres@postgres:5432/drom
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drom
    ports:
      - "5432:5432"
  worker:
    build: .
    command: celery -A app.celery_app.celery worker --loglevel=info --concurrency=1
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres